<?php

/**
 * @file
 * Contains content_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function content_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the content_block module.
    case 'help.page.content_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Display content (via view modes) using fieldable blocks.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function content_block_theme() {
  return [
    'content_block' => [
      'render element' => 'children',
    ],
  ];
}
